#!/bin/bash
set -e

currdir="$(dirname -- ${BASH_SOURCE[0]})"
echo "Installing dotfiles env"

if [ ! -d "$HOME/bin" ]; then
    mkdir "$HOME/bin"
fi

"$currdir/symlink.sh"

"$currdir/deps/index.sh"
"$currdir/git.sh"
"$currdir/zsh.sh"
"$currdir/asdf.sh"

