#!/bin/bash
set -e

script_path="$( cd -- "$(dirname ${BASH_SOURCE[0]})" >/dev/null 2>&1 ; pwd -P )"
root="${script_path%/*}"
echo "Installing dotfiles env"

if [ ! -d "$HOME/bin" ]; then
    mkdir "$HOME/bin"
fi

"$script_path/symlink.sh" "$root"

"$script_path/deps/index.sh"
"$script_path/git.sh"
"$script_path/zsh.sh"
"$script_path/asdf.sh"

